// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineRecruitingPlatform.Model.Database;

namespace OnlineRecruitingPlatform.Model.Database.Migrations
{
    [DbContext(typeof(OnlineRecruitingPlatformDbContext))]
    [Migration("20210509063543_ChangeEntityVacancy")]
    partial class ChangeEntityVacancy
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "B867520A-92DB-4658-BE39-84DA53A601C0",
                            ConcurrencyStamp = "81cf7a06-e88e-4e50-9592-54d9360b8dc8",
                            Name = "Администратор",
                            NormalizedName = "АДМИНИСТРАТОР"
                        },
                        new
                        {
                            Id = "2AABA004-1052-4F53-9EB3-18FA85386AD5",
                            ConcurrencyStamp = "4e052701-4d2f-4884-ae93-b3fb18848f54",
                            Name = "Соискатель",
                            NormalizedName = "СОИСКАТЕЛЬ"
                        },
                        new
                        {
                            Id = "8F525C31-6BCF-460F-86A3-BD51FA76F382",
                            ConcurrencyStamp = "00aa0f6a-71bd-4b08-926f-76de540501c3",
                            Name = "Работодатель",
                            NormalizedName = "РАБОТОДАТЕЛЬ"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "21F7B496-C675-4E8A-A34C-FC5EC0762FDB",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5bcc570b-1de6-427d-9ea5-4f78e1941345",
                            Email = "andrey.levchenko.2001@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ANDREY.LEVCHENKO.2001@GMAIL.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEMBeFg55hEYlHSjt0WbAlSVWAGUOM07y3sWhogUsmd7EJBPpRki0dx2QRp4NMhisow==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "Admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "21F7B496-C675-4E8A-A34C-FC5EC0762FDB",
                            RoleId = "B867520A-92DB-4658-BE39-84DA53A601C0"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Aoguid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BuildingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BuildingName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<Guid?>("StreetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StreetName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("CityId");

                    b.HasIndex("StreetId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.AgePreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdentifierFromAvitoRu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AgePreferences");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.ApplicantCommentAccessType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdentifierFromHeadHunter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ApplicantCommentAccessTypes");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.ApplicantCommentsOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdentifierFromHeadHunter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ApplicantCommentsOrders");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.ApplicantNegotiationStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdentifierFromHeadHunter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ApplicantNegotiationStatuses");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.Area", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Aoguid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("IdentifierFromHeadHunter")
                        .HasColumnType("int");

                    b.Property<int?>("IdentifierFromZarplataRu")
                        .HasColumnType("int");

                    b.Property<int?>("IdentifierParentFromHeadHunter")
                        .HasColumnType("int");

                    b.Property<int?>("IdentifierParentFromZarplataRu")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Aoguid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("IdentifierFromHeadHunter")
                        .HasColumnType("int");

                    b.Property<int?>("IdentifierParentFromHeadHunter")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StreetId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StreetId");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.BusinessTripReadiness", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdentifierFromHeadHunter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BusinessTripReadinessTypes");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdentifierFromAvitoRu")
                        .HasColumnType("int");

                    b.Property<int?>("IdentifierFromHeadHunter")
                        .HasColumnType("int");

                    b.Property<int?>("IdentifierFromZarplataRu")
                        .HasColumnType("int");

                    b.Property<bool?>("IsBlacklisted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsCommerce")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsHolding")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsHr")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.CompanyContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("IdentifierFromZarplataRu")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompanyContacts");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.CompanyContactPhone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CityCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CompanyContactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Formatted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyContactId");

                    b.ToTable("CompanyContactPhones");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.CompanyInformation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BrandedDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardCompanyUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique();

                    b.ToTable("CompanyInformation");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.CompanyInsiderInterview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("IdentifierFromHeadHunter")
                        .HasColumnType("int");

                    b.Property<int?>("IdentifierFromZarplataRu")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompanyInsiderInterviews");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.CompanyLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompanyLocations");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.CompanyLogo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Original")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resolution240px")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resolution90px")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique();

                    b.ToTable("CompanyLogos");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.CompanyPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("IdentifierFromZarplataRu")
                        .HasColumnType("int");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompanyPhotos");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.CompanyRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RelationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("RelationId");

                    b.ToTable("CompanyRelations");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.CompanySubIndustry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubIndustryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("SubIndustryId");

                    b.ToTable("CompanySubIndustries");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("IdentifierFromHeadHunter")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentifierFromHeadHunter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdentifierFromZarplataRu")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.CurrencyQuote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Nominal")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.ToTable("CurrencyQuotes");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.DriverLicenseType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdentifierFromHeadHunter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DriverLicenseTypes");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.EducationLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdentifierFromHeadHunter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdentifierFromZarplataRu")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EducationLevels");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.EmployerActiveVacanciesOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdentifierFromHeadHunter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmployerActiveVacanciesOrders");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.EmployerArchivedVacanciesOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdentifierFromHeadHunter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmployerArchivedVacanciesOrders");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.EmployerRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdentifierFromHeadHunter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmployerRelations");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.EmployerType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdentifierFromHeadHunter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmployerTypes");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.Employment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdentifierFromHeadHunter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdentifierFromZarplataRu")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employments");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.Experience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdentifierFromAvitoRu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentifierFromHeadHunter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdentifierFromZarplataRu")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Experiences");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.Gender", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdentifierFromHeadHunter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genders");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.Industry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Industries");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdentifierFromHeadHunter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.LanguageLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentifierFromHeadHunter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LanguageLevels");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.PaidPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdentifierFromAvitoRu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PaidPeriods");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.PayoutFrequency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdentifierFromAvitoRu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PayoutFrequencies");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.PlaceOfWork", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdentifierFromAvitoRu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PlaceOfWorks");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.Profession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("IdentifierFromZarplataRu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Professions");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.ProfessionalArea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("IdentifierFromAvitoRu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentifierFromHeadHunter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdentifierFromZarplataRu")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProfessionalAreas");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Aoguid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("IdentifierFromHeadHunter")
                        .HasColumnType("int");

                    b.Property<int?>("IdentifierParentFromHeadHunter")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.Relation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Relations");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdentifierFromAvitoRu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentifierFromHeadHunter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdentifierFromZarplataRu")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("IdentifierFromHeadHunter")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.Specialization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("IdentifierFromHeadHunter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdentifierFromZarplataRu")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProfessionalAreaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProfessionalAreaId");

                    b.ToTable("Specializations");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.Street", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Aoguid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("IdentifierFromHeadHunter")
                        .HasColumnType("int");

                    b.Property<int?>("IdentifierParentFromHeadHunter")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Aoguid");

                    b.ToTable("Streets");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.SubIndustry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<Guid>("IndustryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IndustryId");

                    b.ToTable("SubIndustries");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.Vacancy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("AcceptHandicapped")
                        .HasColumnType("bit");

                    b.Property<bool?>("AcceptKids")
                        .HasColumnType("bit");

                    b.Property<bool?>("AcceptPensioner")
                        .HasColumnType("bit");

                    b.Property<bool?>("AcceptStudent")
                        .HasColumnType("bit");

                    b.Property<bool?>("AcceptTemporary")
                        .HasColumnType("bit");

                    b.Property<Guid?>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AgePreferenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Archived")
                        .HasColumnType("bit");

                    b.Property<Guid?>("AreaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EducationLevelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EmploymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExperienceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("IdentifierFromAvitoRu")
                        .HasColumnType("int");

                    b.Property<int?>("IdentifierFromHeadHunter")
                        .HasColumnType("int");

                    b.Property<int?>("IdentifierFromZarplataRu")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PayPeriodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PayoutFrequencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Piecework")
                        .HasColumnType("bit");

                    b.Property<Guid?>("PlaceOfWorkId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProfessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProfessionalAreaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("RemoteInterview")
                        .HasColumnType("bit");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("VacancyTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("VacancyVisibilityTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("WorkingDaysId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("WorkingShiftId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("WorkingTimeIntervalsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("WorkingTimeModesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("AgePreferenceId");

                    b.HasIndex("AreaId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("EducationLevelId");

                    b.HasIndex("EmploymentId");

                    b.HasIndex("ExperienceId");

                    b.HasIndex("PayPeriodId");

                    b.HasIndex("PayoutFrequencyId");

                    b.HasIndex("PlaceOfWorkId");

                    b.HasIndex("ProfessionId");

                    b.HasIndex("ProfessionalAreaId");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("VacancyTypeId");

                    b.HasIndex("VacancyVisibilityTypeId");

                    b.HasIndex("WorkingDaysId");

                    b.HasIndex("WorkingShiftId");

                    b.HasIndex("WorkingTimeIntervalsId");

                    b.HasIndex("WorkingTimeModesId");

                    b.ToTable("Vacancies");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.VacancyBillingType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdentifierFromHeadHunter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VacancyBillingTypes");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.VacancyContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skype")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("VacancyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("VacancyId")
                        .IsUnique();

                    b.ToTable("VacancyContacts");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.VacancyContactPhone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CityCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Formatted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("VacancyContactId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VacancyContactId");

                    b.ToTable("VacancyContactPhones");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.VacancyDriverLicenseType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DriverLicenseTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VacancyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DriverLicenseTypeId");

                    b.HasIndex("VacancyId");

                    b.ToTable("VacancyDriverLicenseTypes");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.VacancyInformation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BrandedDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("HasTest")
                        .HasColumnType("bit");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("VacancyBillingTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VacancyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VacancyBillingTypeId");

                    b.HasIndex("VacancyId")
                        .IsUnique();

                    b.ToTable("VacancyInformation");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.VacancyKeySkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VacancyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("VacancyId");

                    b.ToTable("VacancyKeySkills");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.VacancyRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdentifierFromHeadHunter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VacancyRelations");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.VacancySalary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Bonus")
                        .HasColumnType("float");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Gross")
                        .HasColumnType("bit");

                    b.Property<int?>("LowerWageLimit")
                        .HasColumnType("int");

                    b.Property<int?>("LowerWageLimitRubles")
                        .HasColumnType("int");

                    b.Property<int?>("UpperWageLimit")
                        .HasColumnType("int");

                    b.Property<int?>("UpperWageLimitRubles")
                        .HasColumnType("int");

                    b.Property<Guid>("VacancyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("VacancyId")
                        .IsUnique();

                    b.ToTable("VacancySalaries");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.VacancySpecialization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SpecializationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VacancyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SpecializationId");

                    b.HasIndex("VacancyId");

                    b.ToTable("VacancySpecializations");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.VacancyType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdentifierFromHeadHunter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VacancyTypes");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.VacancyVisibilityType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdentifierFromAvitoRu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VacancyVisibilityTypes");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.WorkingDays", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdentifierFromHeadHunter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WorkingDays");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.WorkingShift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdentifierFromAvitoRu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WorkingShifts");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.WorkingTimeIntervals", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdentifierFromHeadHunter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WorkingTimeIntervals");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.WorkingTimeModes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdentifierFromHeadHunter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WorkingTimeModes");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.Address", b =>
                {
                    b.HasOne("OnlineRecruitingPlatform.Model.Database.Entities.Building", "Building")
                        .WithMany("Addresses")
                        .HasForeignKey("BuildingId");

                    b.HasOne("OnlineRecruitingPlatform.Model.Database.Entities.Area", "Area")
                        .WithMany("Addresses")
                        .HasForeignKey("CityId");

                    b.HasOne("OnlineRecruitingPlatform.Model.Database.Entities.Street", "Street")
                        .WithMany("Addresses")
                        .HasForeignKey("StreetId");

                    b.Navigation("Area");

                    b.Navigation("Building");

                    b.Navigation("Street");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.Area", b =>
                {
                    b.HasOne("OnlineRecruitingPlatform.Model.Database.Entities.Region", "Region")
                        .WithMany("Areas")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.Building", b =>
                {
                    b.HasOne("OnlineRecruitingPlatform.Model.Database.Entities.Street", "Street")
                        .WithMany("Buildings")
                        .HasForeignKey("StreetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Street");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.CompanyContact", b =>
                {
                    b.HasOne("OnlineRecruitingPlatform.Model.Database.Entities.Address", "Address")
                        .WithMany("CompanyContacts")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineRecruitingPlatform.Model.Database.Entities.Company", "Company")
                        .WithMany("CompanyContacts")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.CompanyContactPhone", b =>
                {
                    b.HasOne("OnlineRecruitingPlatform.Model.Database.Entities.CompanyContact", "CompanyContact")
                        .WithMany("CompanyContactPhones")
                        .HasForeignKey("CompanyContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyContact");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.CompanyInformation", b =>
                {
                    b.HasOne("OnlineRecruitingPlatform.Model.Database.Entities.Company", "Company")
                        .WithOne("Information")
                        .HasForeignKey("OnlineRecruitingPlatform.Model.Database.Entities.CompanyInformation", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.CompanyInsiderInterview", b =>
                {
                    b.HasOne("OnlineRecruitingPlatform.Model.Database.Entities.Company", "Company")
                        .WithMany("InsiderInterviews")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.CompanyLocation", b =>
                {
                    b.HasOne("OnlineRecruitingPlatform.Model.Database.Entities.Area", "Area")
                        .WithMany("CompanyLocations")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineRecruitingPlatform.Model.Database.Entities.Company", "Company")
                        .WithMany("Locations")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.CompanyLogo", b =>
                {
                    b.HasOne("OnlineRecruitingPlatform.Model.Database.Entities.Company", "Company")
                        .WithOne("Logo")
                        .HasForeignKey("OnlineRecruitingPlatform.Model.Database.Entities.CompanyLogo", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.CompanyPhoto", b =>
                {
                    b.HasOne("OnlineRecruitingPlatform.Model.Database.Entities.Company", "Company")
                        .WithMany("CompanyPhotos")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.CompanyRelation", b =>
                {
                    b.HasOne("OnlineRecruitingPlatform.Model.Database.Entities.Company", "Company")
                        .WithMany("Relations")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineRecruitingPlatform.Model.Database.Entities.Relation", "Relation")
                        .WithMany("CompanyRelations")
                        .HasForeignKey("RelationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Relation");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.CompanySubIndustry", b =>
                {
                    b.HasOne("OnlineRecruitingPlatform.Model.Database.Entities.Company", "Company")
                        .WithMany("SubIndustries")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineRecruitingPlatform.Model.Database.Entities.SubIndustry", "SubIndustry")
                        .WithMany("CompanySubIndustries")
                        .HasForeignKey("SubIndustryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("SubIndustry");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.CurrencyQuote", b =>
                {
                    b.HasOne("OnlineRecruitingPlatform.Model.Database.Entities.Currency", "Currency")
                        .WithMany("CurrencyQuotes")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.Region", b =>
                {
                    b.HasOne("OnlineRecruitingPlatform.Model.Database.Entities.Country", "Country")
                        .WithMany("Regions")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.Specialization", b =>
                {
                    b.HasOne("OnlineRecruitingPlatform.Model.Database.Entities.ProfessionalArea", "ProfessionalArea")
                        .WithMany("Specializations")
                        .HasForeignKey("ProfessionalAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProfessionalArea");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.Street", b =>
                {
                    b.HasOne("OnlineRecruitingPlatform.Model.Database.Entities.Area", "Area")
                        .WithMany("Streets")
                        .HasForeignKey("Aoguid");

                    b.Navigation("Area");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.SubIndustry", b =>
                {
                    b.HasOne("OnlineRecruitingPlatform.Model.Database.Entities.Industry", "Industry")
                        .WithMany("SubIndustries")
                        .HasForeignKey("IndustryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Industry");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.Vacancy", b =>
                {
                    b.HasOne("OnlineRecruitingPlatform.Model.Database.Entities.Address", "Address")
                        .WithMany("Vacancies")
                        .HasForeignKey("AddressId");

                    b.HasOne("OnlineRecruitingPlatform.Model.Database.Entities.AgePreference", "AgePreference")
                        .WithMany("Vacancies")
                        .HasForeignKey("AgePreferenceId");

                    b.HasOne("OnlineRecruitingPlatform.Model.Database.Entities.Area", "Area")
                        .WithMany("Vacancies")
                        .HasForeignKey("AreaId");

                    b.HasOne("OnlineRecruitingPlatform.Model.Database.Entities.Company", "Company")
                        .WithMany("Vacancies")
                        .HasForeignKey("CompanyId");

                    b.HasOne("OnlineRecruitingPlatform.Model.Database.Entities.EducationLevel", "EducationLevel")
                        .WithMany("Vacancies")
                        .HasForeignKey("EducationLevelId");

                    b.HasOne("OnlineRecruitingPlatform.Model.Database.Entities.Employment", "Employment")
                        .WithMany("Vacancies")
                        .HasForeignKey("EmploymentId");

                    b.HasOne("OnlineRecruitingPlatform.Model.Database.Entities.Experience", "Experience")
                        .WithMany("Vacancies")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineRecruitingPlatform.Model.Database.Entities.PaidPeriod", "PayPeriod")
                        .WithMany("Vacancies")
                        .HasForeignKey("PayPeriodId");

                    b.HasOne("OnlineRecruitingPlatform.Model.Database.Entities.PayoutFrequency", "PayoutFrequency")
                        .WithMany("Vacancies")
                        .HasForeignKey("PayoutFrequencyId");

                    b.HasOne("OnlineRecruitingPlatform.Model.Database.Entities.PlaceOfWork", "PlaceOfWork")
                        .WithMany("Vacancies")
                        .HasForeignKey("PlaceOfWorkId");

                    b.HasOne("OnlineRecruitingPlatform.Model.Database.Entities.Profession", "Profession")
                        .WithMany("Vacancies")
                        .HasForeignKey("ProfessionId");

                    b.HasOne("OnlineRecruitingPlatform.Model.Database.Entities.ProfessionalArea", "ProfessionalArea")
                        .WithMany("Vacancies")
                        .HasForeignKey("ProfessionalAreaId");

                    b.HasOne("OnlineRecruitingPlatform.Model.Database.Entities.Schedule", "Schedule")
                        .WithMany("Vacancies")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineRecruitingPlatform.Model.Database.Entities.VacancyType", "VacancyType")
                        .WithMany("Vacancies")
                        .HasForeignKey("VacancyTypeId");

                    b.HasOne("OnlineRecruitingPlatform.Model.Database.Entities.VacancyVisibilityType", "VacancyVisibilityType")
                        .WithMany("Vacancies")
                        .HasForeignKey("VacancyVisibilityTypeId");

                    b.HasOne("OnlineRecruitingPlatform.Model.Database.Entities.WorkingDays", "WorkingDays")
                        .WithMany("Vacancies")
                        .HasForeignKey("WorkingDaysId");

                    b.HasOne("OnlineRecruitingPlatform.Model.Database.Entities.WorkingShift", "WorkingShift")
                        .WithMany("Vacancies")
                        .HasForeignKey("WorkingShiftId");

                    b.HasOne("OnlineRecruitingPlatform.Model.Database.Entities.WorkingTimeIntervals", "WorkingTimeIntervals")
                        .WithMany("Vacancies")
                        .HasForeignKey("WorkingTimeIntervalsId");

                    b.HasOne("OnlineRecruitingPlatform.Model.Database.Entities.WorkingTimeModes", "WorkingTimeModes")
                        .WithMany("Vacancies")
                        .HasForeignKey("WorkingTimeModesId");

                    b.Navigation("Address");

                    b.Navigation("AgePreference");

                    b.Navigation("Area");

                    b.Navigation("Company");

                    b.Navigation("EducationLevel");

                    b.Navigation("Employment");

                    b.Navigation("Experience");

                    b.Navigation("PayoutFrequency");

                    b.Navigation("PayPeriod");

                    b.Navigation("PlaceOfWork");

                    b.Navigation("Profession");

                    b.Navigation("ProfessionalArea");

                    b.Navigation("Schedule");

                    b.Navigation("VacancyType");

                    b.Navigation("VacancyVisibilityType");

                    b.Navigation("WorkingDays");

                    b.Navigation("WorkingShift");

                    b.Navigation("WorkingTimeIntervals");

                    b.Navigation("WorkingTimeModes");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.VacancyContact", b =>
                {
                    b.HasOne("OnlineRecruitingPlatform.Model.Database.Entities.Address", "Address")
                        .WithMany("VacancyContacts")
                        .HasForeignKey("AddressId");

                    b.HasOne("OnlineRecruitingPlatform.Model.Database.Entities.Vacancy", "Vacancy")
                        .WithOne("VacancyContact")
                        .HasForeignKey("OnlineRecruitingPlatform.Model.Database.Entities.VacancyContact", "VacancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.VacancyContactPhone", b =>
                {
                    b.HasOne("OnlineRecruitingPlatform.Model.Database.Entities.VacancyContact", "VacancyContact")
                        .WithMany("VacancyContactPhones")
                        .HasForeignKey("VacancyContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VacancyContact");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.VacancyDriverLicenseType", b =>
                {
                    b.HasOne("OnlineRecruitingPlatform.Model.Database.Entities.DriverLicenseType", "DriverLicenseType")
                        .WithMany("VacancyDriverLicenseTypes")
                        .HasForeignKey("DriverLicenseTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineRecruitingPlatform.Model.Database.Entities.Vacancy", "Vacancy")
                        .WithMany("VacancyDriverLicenseTypes")
                        .HasForeignKey("VacancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DriverLicenseType");

                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.VacancyInformation", b =>
                {
                    b.HasOne("OnlineRecruitingPlatform.Model.Database.Entities.VacancyBillingType", "VacancyBillingType")
                        .WithMany("VacancyInformation")
                        .HasForeignKey("VacancyBillingTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineRecruitingPlatform.Model.Database.Entities.Vacancy", "Vacancy")
                        .WithOne("VacancyInformation")
                        .HasForeignKey("OnlineRecruitingPlatform.Model.Database.Entities.VacancyInformation", "VacancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vacancy");

                    b.Navigation("VacancyBillingType");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.VacancyKeySkill", b =>
                {
                    b.HasOne("OnlineRecruitingPlatform.Model.Database.Entities.Skill", "Skill")
                        .WithMany("VacancyKeySkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineRecruitingPlatform.Model.Database.Entities.Vacancy", "Vacancy")
                        .WithMany("VacancyKeySkills")
                        .HasForeignKey("VacancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.VacancySalary", b =>
                {
                    b.HasOne("OnlineRecruitingPlatform.Model.Database.Entities.Currency", "Currency")
                        .WithMany("VacancySalaries")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineRecruitingPlatform.Model.Database.Entities.Vacancy", "Vacancy")
                        .WithOne("VacancySalary")
                        .HasForeignKey("OnlineRecruitingPlatform.Model.Database.Entities.VacancySalary", "VacancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.VacancySpecialization", b =>
                {
                    b.HasOne("OnlineRecruitingPlatform.Model.Database.Entities.Specialization", "Specialization")
                        .WithMany("VacancySpecializations")
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineRecruitingPlatform.Model.Database.Entities.Vacancy", "Vacancy")
                        .WithMany("VacancySpecializations")
                        .HasForeignKey("VacancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Specialization");

                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.Address", b =>
                {
                    b.Navigation("CompanyContacts");

                    b.Navigation("Vacancies");

                    b.Navigation("VacancyContacts");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.AgePreference", b =>
                {
                    b.Navigation("Vacancies");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.Area", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("CompanyLocations");

                    b.Navigation("Streets");

                    b.Navigation("Vacancies");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.Building", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.Company", b =>
                {
                    b.Navigation("CompanyContacts");

                    b.Navigation("CompanyPhotos");

                    b.Navigation("Information");

                    b.Navigation("InsiderInterviews");

                    b.Navigation("Locations");

                    b.Navigation("Logo");

                    b.Navigation("Relations");

                    b.Navigation("SubIndustries");

                    b.Navigation("Vacancies");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.CompanyContact", b =>
                {
                    b.Navigation("CompanyContactPhones");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.Country", b =>
                {
                    b.Navigation("Regions");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.Currency", b =>
                {
                    b.Navigation("CurrencyQuotes");

                    b.Navigation("VacancySalaries");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.DriverLicenseType", b =>
                {
                    b.Navigation("VacancyDriverLicenseTypes");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.EducationLevel", b =>
                {
                    b.Navigation("Vacancies");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.Employment", b =>
                {
                    b.Navigation("Vacancies");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.Experience", b =>
                {
                    b.Navigation("Vacancies");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.Industry", b =>
                {
                    b.Navigation("SubIndustries");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.PaidPeriod", b =>
                {
                    b.Navigation("Vacancies");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.PayoutFrequency", b =>
                {
                    b.Navigation("Vacancies");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.PlaceOfWork", b =>
                {
                    b.Navigation("Vacancies");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.Profession", b =>
                {
                    b.Navigation("Vacancies");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.ProfessionalArea", b =>
                {
                    b.Navigation("Specializations");

                    b.Navigation("Vacancies");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.Region", b =>
                {
                    b.Navigation("Areas");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.Relation", b =>
                {
                    b.Navigation("CompanyRelations");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.Schedule", b =>
                {
                    b.Navigation("Vacancies");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.Skill", b =>
                {
                    b.Navigation("VacancyKeySkills");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.Specialization", b =>
                {
                    b.Navigation("VacancySpecializations");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.Street", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Buildings");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.SubIndustry", b =>
                {
                    b.Navigation("CompanySubIndustries");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.Vacancy", b =>
                {
                    b.Navigation("VacancyContact");

                    b.Navigation("VacancyDriverLicenseTypes");

                    b.Navigation("VacancyInformation");

                    b.Navigation("VacancyKeySkills");

                    b.Navigation("VacancySalary");

                    b.Navigation("VacancySpecializations");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.VacancyBillingType", b =>
                {
                    b.Navigation("VacancyInformation");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.VacancyContact", b =>
                {
                    b.Navigation("VacancyContactPhones");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.VacancyType", b =>
                {
                    b.Navigation("Vacancies");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.VacancyVisibilityType", b =>
                {
                    b.Navigation("Vacancies");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.WorkingDays", b =>
                {
                    b.Navigation("Vacancies");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.WorkingShift", b =>
                {
                    b.Navigation("Vacancies");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.WorkingTimeIntervals", b =>
                {
                    b.Navigation("Vacancies");
                });

            modelBuilder.Entity("OnlineRecruitingPlatform.Model.Database.Entities.WorkingTimeModes", b =>
                {
                    b.Navigation("Vacancies");
                });
#pragma warning restore 612, 618
        }
    }
}
